/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.assignment;

/**
 * Main class declaration from which whole program begins.
 */
public final class App {

  /**
   * Main program which takes command line arguments.
   *
   * @param args string arguments.
   */
  public static void main(final String[] args) {
    final UserManager userManager = new UserManager();
    userManager.startManager();

  }

  private App() {

  }

}
