/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment;

import com.assignment.models.Graph;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void unitTest() {
        App classUnderTest = new App();

        Graph graph =new Graph();
        try{
            System.setIn(new FileInputStream("C:\\Users\\Tanmay Shukla\\IdeaProjects\\AssignmentThree\\app\\src\\test\\java\\com\\assignment\\graph-input.txt"));
            BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
            graph.inputGraph();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        ArrayList<Integer>arrayList=new ArrayList<>();
        arrayList.add(2);
        assertEquals(arrayList,graph.getImmediateParents(3),"Parent must be same");
        assertEquals(arrayList,graph.getImmediateChildren(1),"Children must be same");
        arrayList.add(1);
        assertEquals(arrayList,graph.getAncestors(3),"Ancestors must be same");
        ArrayList<Integer>arrayList1=new ArrayList<>();
        arrayList1.add(3);
        arrayList1.add(4);
        assertEquals(arrayList1,graph.getDescendants(2),"Descendants must be same");
    }
}
